name: 'swift-package-dependencies-check'
description: 'Catch up with outdated versions based on your package dependency requirements'
branding:
  icon: "package"
  color: "purple"
inputs:
  isMutating:
    description: 'Modfiy Package.resolved in case of new versions'
    required: false
    default: false
outputs:
  releaseNotes:
    description: 'Textual result of SwiftPackageIndex/ReleaseNotes'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.isMutating }}
